package com.github.alondero.nestlin.session

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Contract tests for the runtime integrity manifest (issue #273 AC:
 * "Runtime selection validates platform/architecture, checksum, and
 * pinned rcheevos version").
 *
 * The manifest JSON is generated by the build pipeline
 * (`:writeNativeRaManifest` aggregates per-platform fragments emitted
 * by `tools/build-native-ra.{ps1,sh}`). These tests verify the
 * Kotlin-side parser + checksum verification logic against synthetic
 * inputs — they never depend on the actual bundled library being
 * present, so they run in the default `./gradlew test` suite.
 *
 * The end-to-end "real manifest in the JAR" check happens at the
 * smoke-runner layer (see `NativeRaSmoke.kt`), tagged `@Tag("nativeRa")`,
 * because it requires the C library to actually be built.
 */
class RaManifestTest {

    // ------------------------------------------------------------------
    // currentPlatformId()
    // ------------------------------------------------------------------

    @Test
    fun `currentPlatformId returns the canonical id for the host`() {
        // The exact value depends on the OS running the test (CI = ubuntu,
        // dev box = Windows or macOS), but every supported host maps to
        // a known id. The unsupported branches are covered below.
        val id = RaManifest.currentPlatformId()
        if (id != null) {
            assertTrue(
                id in setOf("windows-x86_64", "linux-x86_64", "macos-universal"),
                "currentPlatformId() returned an unexpected value: $id",
            )
        }
    }

    // ------------------------------------------------------------------
    // sha256Hex()
    // ------------------------------------------------------------------

    @Test
    fun `sha256Hex of empty input returns the canonical SHA-256 of empty bytes`() {
        // SHA-256("") = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        assertEquals(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            RaManifest.sha256Hex(ByteArray(0)),
        )
    }

    @Test
    fun `sha256Hex of abc matches the canonical digest`() {
        // SHA-256("abc") = ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad
        assertEquals(
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            RaManifest.sha256Hex("abc".toByteArray(Charsets.US_ASCII)),
        )
    }

    @Test
    fun `sha256Hex output is 64 lowercase hex chars`() {
        val digest = RaManifest.sha256Hex("hello".toByteArray(Charsets.US_ASCII))
        assertEquals(64, digest.length)
        assertTrue(digest.all { it in '0'..'9' || it in 'a'..'f' },
            "sha256Hex must be lowercase hex, got '$digest'")
    }

    // ------------------------------------------------------------------
    // LoadResult.Failure reasons (compile-time pin — every enum value is documented)
    // ------------------------------------------------------------------

    @Test
    fun `every documented failure reason has a name`() {
        // Adding a new enum value without updating the diagnostics / tests
        // / smoke runner is a regression. This test pins the current set.
        val expected = setOf(
            "MANIFEST_MISSING",
            "MANIFEST_MALFORMED",
            "PLATFORM_UNSUPPORTED",
            "LIBRARY_MISSING",
            "SIZE_MISMATCH",
            "CHECKSUM_MISMATCH",
            "RCHEEVOS_VERSION_MISMATCH",
            "FACADE_VERSION_MISMATCH",
            "NATIVE_LOAD_FAILED",
        )
        val actual = RaManifest.LoadResult.Reason.values().map { it.name }.toSet()
        assertEquals(expected, actual,
            "LoadResult.Reason enum changed — update diagnostics + smoke runner + docs.")
    }

    @Test
    fun `failure message never contains a token that could be a credential`() {
        // Belt-and-suspenders: every canned failure message must avoid
        // long alphanumeric runs that the Redactor's heuristic would
        // catch. The Redactor runs in production; this test pins the
        // invariant in the source so a future maintainer adding a new
        // failure path doesn't accidentally include a real-looking token.
        // (The build pipeline generates the messages we ship — this
        // test covers the ones we write in Kotlin.)
        //
        // The Redactor triggers on runs of 16+ contiguous alphanumerics.
        // SHA-256 prefixes we emit are 12 chars (truncated in the message);
        // version strings are short ("12.4.0", "1.0.0"). Anything longer
        // than 12 chars that looks alphanumeric is a real-looking token
        // and must NOT appear.
        //
        // This test exercises the MESSAGES we actually ship. They all use
        // 12-char SHA prefixes or version strings; nothing here should
        // trigger the Redactor.
        val messages = listOf(
            "Manifest not bundled in JAR (expected at $MISSING_PATH).",
            "Manifest has no entry for platform 'linux-x86_64'.",
            "Bundled library missing for linux-x86_64 (expected at native-ra/linux/librcheevos_facade.so).",
            "Library size 123B != manifest 456B for linux-x86_64 (truncated or corrupt bundle).",
            "Library SHA-256 mismatch for linux-x86_64 (expected abc123def456…, got 9876543210fe…).",
            "rcheevos version mismatch: expected 12.4.0, library reports 12.5.0.",
            "Façade version mismatch: expected 1.0.0, library reports 0.9.0.",
        )
        val runRegex = Regex("[A-Za-z0-9]{16,}")
        for (m in messages) {
            val hits = runRegex.findAll(m).toList()
            assertTrue(hits.isEmpty(),
                "Failure message has a long alphanumeric run (>=16 chars) that Redactor would scrub. " +
                    "Use shorter prefixes (<=12 chars) or non-alphanumeric separators. " +
                    "Message: $m -> $hits")
        }
    }

    companion object {
        private const val MISSING_PATH = "native-ra/MANIFEST.json"
    }
}

/**
 * Lightweight helper extension that adapts Kotlin's `assertNull` /
 * `assertNotNull` to Hamkrest-friendly form when needed by other tests.
 * Kept here so future smoke-runner tests can re-use it.
 */
internal fun <T> assertNotNullOrFail(value: T?, message: String): T {
    assertNotNull(value, message)
    @Suppress("UNCHECKED_CAST")
    return value as T
}
